// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThesisWebApp.Data;

#nullable disable

namespace ThesisWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328221246_InitialFullSchema")]
    partial class InitialFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThesisWebApp.Models.LokacijaPredef", b =>
                {
                    b.Property<string>("Ime")
                        .HasColumnType("text")
                        .HasColumnName("ime");

                    b.Property<int>("MostId")
                        .HasColumnType("integer")
                        .HasColumnName("most_id");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uloga");

                    b.Property<double?>("XKoord")
                        .HasColumnType("double precision")
                        .HasColumnName("x_koord");

                    b.Property<double?>("YKoord")
                        .HasColumnType("double precision")
                        .HasColumnName("y_koord");

                    b.Property<double?>("ZKoord")
                        .HasColumnType("double precision")
                        .HasColumnName("z_koord");

                    b.HasKey("Ime");

                    b.HasIndex("MostId");

                    b.ToTable("lokacije_predef");
                });

            modelBuilder.Entity("ThesisWebApp.Models.Merenje", b =>
                {
                    b.Property<string>("Ime")
                        .HasColumnType("text")
                        .HasColumnName("ime");

                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("dt");

                    b.Property<double?>("D3d")
                        .HasColumnType("double precision")
                        .HasColumnName("d3d");

                    b.Property<double?>("Dx")
                        .HasColumnType("double precision")
                        .HasColumnName("dx");

                    b.Property<double?>("Dy")
                        .HasColumnType("double precision")
                        .HasColumnName("dy");

                    b.Property<double?>("Dz")
                        .HasColumnType("double precision")
                        .HasColumnName("dz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<double?>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double?>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.Property<double?>("Z")
                        .HasColumnType("double precision")
                        .HasColumnName("z");

                    b.HasKey("Ime", "Dt");

                    b.ToTable("merenja");
                });

            modelBuilder.Entity("ThesisWebApp.Models.Most", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("LimitAlarma")
                        .HasColumnType("double precision")
                        .HasColumnName("limit_alarma");

                    b.Property<double>("LimitSrel")
                        .HasColumnType("double precision")
                        .HasColumnName("limit_srel");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("naziv");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip");

                    b.HasKey("Id");

                    b.ToTable("mostovi");
                });

            modelBuilder.Entity("ThesisWebApp.Models.Postavke", b =>
                {
                    b.Property<string>("Kljuc")
                        .HasColumnType("text")
                        .HasColumnName("kljuc");

                    b.Property<string>("Vrednost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vrednost");

                    b.HasKey("Kljuc");

                    b.ToTable("postavke");
                });

            modelBuilder.Entity("ThesisWebApp.Models.LokacijaPredef", b =>
                {
                    b.HasOne("ThesisWebApp.Models.Most", "Most")
                        .WithMany("Lokacije")
                        .HasForeignKey("MostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Most");
                });

            modelBuilder.Entity("ThesisWebApp.Models.Merenje", b =>
                {
                    b.HasOne("ThesisWebApp.Models.LokacijaPredef", "Lokacija")
                        .WithMany("Merenja")
                        .HasForeignKey("Ime")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lokacija");
                });

            modelBuilder.Entity("ThesisWebApp.Models.LokacijaPredef", b =>
                {
                    b.Navigation("Merenja");
                });

            modelBuilder.Entity("ThesisWebApp.Models.Most", b =>
                {
                    b.Navigation("Lokacije");
                });
#pragma warning restore 612, 618
        }
    }
}
